"""Build the interactive live-view HTML — a port of the JS ``lib/render.js``.

The browser CSS and runtime JS are shared verbatim with the JS renderer via
``_assets.py`` (regenerated by ``tools/extract-assets.mjs``); this module only
generates the per-node HTML (overlays, panels, source tree, selection rules).
"""

from __future__ import annotations

import base64
from typing import Optional, Union

from ._assets import BASE_CSS, RUNTIME_JS
from ._locators import suggest_locators
from ._parse import Node, parse_source

_TIP_ATTRS = ["resource-id", "content-desc", "text", "name", "label", "value", "type", "class"]


def _escape(value) -> str:
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


def _xml_attr_escape(value) -> str:
    return str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _pct(part: float, whole: float) -> str:
    return f"{(part / whole * 100):.4f}%" if whole > 0 else "0%"


def _has_rect(node: Node) -> bool:
    return bool(node.rect and node.rect["w"] > 0 and node.rect["h"] > 0)


def _is_box(node: Node) -> bool:
    # Overlay only for elements shown on the screenshot AND that are accessibility
    # elements. iOS marks occluded / not-scrolled-in elements visible="false"
    # (phantom overlays) and layout containers accessible="false" (deep-nesting
    # clutter); both are still selectable via the source tree. iOS-only attributes,
    # so Android is unaffected (its equivalent of visible is displayed).
    a = node.attributes
    return bool(
        _has_rect(node)
        and a.get("visible") != "false"
        and a.get("displayed") != "false"
        and a.get("accessible") != "false"
    )


def _tip_label(node: Node) -> str:
    a = node.attributes or {}
    for key in _TIP_ATTRS:
        if a.get(key):
            return f"{node.tag_name} · {a[key]}"
    return node.tag_name


def _serialize_element(node: Node) -> str:
    attrs = "".join(f' {k}="{_xml_attr_escape(v)}"' for k, v in node.attributes.items())
    kids = "".join(_serialize_element(c) for c in node.children)
    return f"<{node.tag_name}{attrs}>{kids}</{node.tag_name}>"


def _normalize_screenshot(screenshot: Union[bytes, bytearray, str, None]) -> str:
    if not screenshot:
        return ""
    if isinstance(screenshot, (bytes, bytearray)):
        return "data:image/png;base64," + base64.b64encode(bytes(screenshot)).decode("ascii")
    if screenshot.startswith("data:"):
        return screenshot
    return f"data:image/png;base64,{screenshot}"


def _render_panel(node: Node) -> str:
    attrs = node.attributes or {}
    rows = "".join(f"<tr><th>{_escape(k)}</th><td>{_escape(v)}</td></tr>" for k, v in attrs.items())
    locators = "".join(
        f'''
        <li class="lv-loc" data-copy="{_escape(loc["value"])}" title="Click to copy">
          <div class="lv-loc-head"><span class="lv-loc-type">{_escape(loc["type"])}</span>
            <span class="lv-loc-hint">click to copy</span></div>
          <code class="lv-loc-value">{_escape(loc["value"])}</code>
        </li>'''
        for loc in suggest_locators(node)
    )
    rect = (
        f'<div class="lv-rect">x {node.rect["x1"]}, y {node.rect["y1"]} · {node.rect["w"]}×{node.rect["h"]}</div>'
        if node.rect
        else ""
    )
    return f'''
    <div class="lv-panel lv-panel-{node.index}">
      <div class="lv-panel-head"><span class="lv-tag">{_escape(node.tag_name)}</span>{rect}</div>
      <div class="lv-sub">Suggested locators</div>
      <ul class="lv-locators">{locators}</ul>
      <div class="lv-sub">Attributes</div>
      <table class="lv-attrs">{rows}</table>
    </div>'''


def build_live_view_html(
    xml: Optional[str] = None,
    screenshot: Union[bytes, bytearray, str, None] = None,
    *,
    title: Optional[str] = None,
    platform_name: Optional[str] = None,
    selected_path: Optional[str] = None,
    parsed: Optional[dict] = None,
) -> str:
    """Render page source + screenshot into a standalone, interactive HTML page.

    ``screenshot`` may be raw PNG bytes (e.g. ``driver.get_screenshot_as_png()``),
    a base64 string (``get_screenshot_as_base64()``), or a full ``data:`` URI.
    Returns a complete HTML document ready to attach, e.g.::

        allure.attach(html, "Live view", allure.attachment_type.HTML)
    """
    parsed = parsed or parse_source(xml or "")
    nodes: list[Node] = parsed["nodes"]
    extents = parsed["extents"]
    root = parsed["root"]
    drawable = [n for n in nodes if _is_box(n)]
    shot = _normalize_screenshot(screenshot)
    title = title or "Appium live view"

    xml_b64 = ""
    if root is not None:
        source = '<?xml version="1.0" encoding="UTF-8"?>' + _serialize_element(root)
        xml_b64 = base64.b64encode(source.encode("utf-8")).decode("ascii")

    selected = None
    if selected_path is not None:
        selected = next((n for n in nodes if n.path == selected_path), None)

    radios = "\n".join(
        [
            '<input type="checkbox" id="lv-tree-toggle" class="lv-r">',
            f'<input type="radio" name="lv-sel" id="lv-none" class="lv-r"{"" if selected else " checked"}>',
            *[
                f'<input type="radio" name="lv-sel" id="lv-r-{n.index}" class="lv-r"'
                f'{" checked" if (selected and selected.index == n.index) else ""}>'
                for n in nodes
            ],
        ]
    )

    def _on_screen(n: Node) -> bool:
        r = n.rect
        return r["x1"] >= 0 and r["y1"] >= 0 and r["x2"] <= extents["width"] and r["y2"] <= extents["height"]

    # smaller-area elements sit above larger ones at the same depth (see render.js)
    area_rank: dict = {}
    for i, n in enumerate(sorted((x for x in nodes if _has_rect(x)), key=lambda x: -(x.rect["w"] * x.rect["h"]))):
        area_rank[n.index] = min(i, 999)

    def _z_index(n: Node) -> int:
        # onScreen? then depth then smaller-area rank (special layers live above)
        return (1000000 if _on_screen(n) else 0) + n.depth * 1000 + area_rank.get(n.index, 0)

    def _overlay(n: Node) -> str:
        r = n.rect
        style = (
            f'left:{_pct(r["x1"], extents["width"])};top:{_pct(r["y1"], extents["height"])};'
            f'width:{_pct(r["w"], extents["width"])};height:{_pct(r["h"], extents["height"])};z-index:{_z_index(n)}'
        )
        if _is_box(n):
            return (
                f'<label class="lv-el lv-el-{n.index}" for="lv-r-{n.index}" style="{style}">'
                f'<span class="lv-tip">{_escape(_tip_label(n))}</span></label>'
            )
        # occluded / non-accessibility element: a dotted outline only when selected
        return f'<label class="lv-ghost lv-el-{n.index}" for="lv-r-{n.index}" style="{style}"></label>'

    overlays = "\n".join(_overlay(n) for n in nodes if _has_rect(n))

    def _tree_row(n: Node) -> str:
        a = n.attributes or {}
        key = a.get("resource-id") or a.get("content-desc") or a.get("text") or a.get("name") or a.get("label") or a.get("value") or ""
        attr = f' <span class="lv-node-attr">{_escape(str(key)[:40])}</span>' if key else ""
        nobox = "" if _is_box(n) else ' <span class="lv-node-nobox" title="not shown on the screenshot — select here to inspect">◌</span>'
        return (
            f'<label class="lv-node lv-node-{n.index}" for="lv-r-{n.index}" style="padding-left:{6 + n.depth * 13}px" title="{_escape(n.tag_name)}">'
            f'<span class="lv-node-tag">{_escape(n.tag_name)}</span>{attr}{nobox}</label>'
        )

    tree_rows = "\n".join(_tree_row(n) for n in nodes)
    panels = "\n".join(_render_panel(n) for n in nodes)

    def _selection_rule(n: Node) -> str:
        css = (
            f"#lv-r-{n.index}:checked~.lv-main .lv-panel-{n.index}{{display:block}}"
            f"#lv-r-{n.index}:checked~.lv-main .lv-node-{n.index}{{background:rgba(229,72,77,.18);outline:1px solid rgba(229,72,77,.5)}}"
        )
        if _is_box(n):
            css += f"#lv-r-{n.index}:checked~.lv-main .lv-el-{n.index}{{outline:2px solid #e5484d;background:rgba(229,72,77,.16)}}"
        elif _has_rect(n):
            css += f"#lv-r-{n.index}:checked~.lv-main .lv-el-{n.index}{{display:block;outline:2px dotted #e5484d;background:rgba(229,72,77,.1);z-index:2000000}}"
        return css

    selection_css = "".join(_selection_rule(n) for n in nodes)

    meta = " · ".join(
        p
        for p in [
            _escape(platform_name) if platform_name else None,
            f"{len(drawable)} elements",
            f'{extents["width"]}×{extents["height"]}' if extents["width"] and extents["height"] else None,
        ]
        if p
    )

    tools = ""
    if nodes or xml_b64 or shot:
        source_btn = (
            '<label for="lv-tree-toggle" class="lv-btn lv-btn-src" title="Show the source tree — every node is selectable, including ones without bounds">Source</label>'
            if nodes
            else ""
        )
        xml_btn = (
            '<a id="lv-xml" class="lv-btn" download="page-source.xml" title="Download the page source (XML). The Source tree shows it in place.">XML</a>'
            if xml_b64
            else ""
        )
        img_btn = (
            '<a id="lv-img" class="lv-btn" download="screenshot" title="Download the screenshot">Image</a>' if shot else ""
        )
        tools = f'<span class="lv-tools">{source_btn}{xml_btn}{img_btn}</span>'

    aspect = f'{extents["width"] or 9} / {extents["height"] or 16}'
    stage_inner = (f'<img class="lv-shot" src="{shot}" alt="screenshot">' if shot else "") + overlays

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_escape(title)}</title>
</head>
<body>
<style>{BASE_CSS}{selection_css}</style>
<div class="lv-root" data-appium-live-view="1" data-src="{xml_b64}">
{radios}
<div class="lv-head">
  <h1>{_escape(title)}</h1>
  <span class="lv-meta">{meta}</span>
  {tools}
  <span class="lv-xpath">
    <input type="text" id="lv-xpath" placeholder="Test XPath, e.g. //*[@text='OK']" autocomplete="off" spellcheck="false">
    <span class="lv-xpath-status" id="lv-xstat"></span>
  </span>
</div>
<div class="lv-main">
  <div class="lv-stage" style="aspect-ratio:{aspect}">
    {stage_inner}
  </div>
  <nav class="lv-tree" aria-label="Source tree">
    <div class="lv-tree-head">Source tree · {len(nodes)} nodes</div>
    <div class="lv-tree-body">{tree_rows}</div>
  </nav>
  <div class="lv-side">
    <div class="lv-panel lv-panel-none">Hover an element to preview it; click to pin its attributes and locators here.</div>
    {panels}
  </div>
</div>
</div>
<script>{RUNTIME_JS}</script>
</body>
</html>"""
