// Extract the browser CSS + runtime JS from lib/render.js into the Python
// package, so the Python renderer shares them verbatim with the JS one.
// Re-run after changing the <style> or <script> in lib/render.js:
//
//   node tools/extract-assets.mjs
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { buildLiveViewHtml } from "../lib/render.js";

// Rendering with no source yields the static CSS (empty per-node selection rules)
// and the full runtime script — exactly the parts that are language-independent.
const html = buildLiveViewHtml({ xml: "", screenshot: "" });
const css = html.match(/<style>([\s\S]*?)<\/style>/)[1];
const js = html.match(/<script>([\s\S]*?)<\/script>/)[1];

// JSON.stringify output is also a valid Python string literal.
const out =
  "# Auto-generated by tools/extract-assets.mjs — do not edit by hand.\n" +
  "# The browser CSS and runtime JS from lib/render.js, shared verbatim by the\n" +
  "# JS and Python renderers. Re-run `node tools/extract-assets.mjs` after editing\n" +
  "# the <style> or <script> in lib/render.js.\n\n" +
  `BASE_CSS = ${JSON.stringify(css)}\n\n` +
  `RUNTIME_JS = ${JSON.stringify(js)}\n`;

const dest = fileURLToPath(new URL("../python/src/appium_live_view/_assets.py", import.meta.url));
writeFileSync(dest, out);
console.log(`wrote ${dest} — css ${css.length} chars, js ${js.length} chars`);
